// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6KJGbIM_bQF9wgH90j6JXmjAnnWEw0i8',
    appId: '1:76949227612:web:640993e8e85b8934003e99',
    messagingSenderId: '76949227612',
    projectId: 'comparador-ff653',
    authDomain: 'comparador-ff653.firebaseapp.com',
    storageBucket: 'comparador-ff653.firebasestorage.app',
    measurementId: 'G-JN8TY6LBDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaFkCos4V6mZ-xYNCH7Jl8A2ELPRZTL9g',
    appId: '1:76949227612:android:53c10743c2e7e1a3003e99',
    messagingSenderId: '76949227612',
    projectId: 'comparador-ff653',
    storageBucket: 'comparador-ff653.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN0j6RSdN3UTVHMPVkVCWIg6Rn-FQgguM',
    appId: '1:76949227612:ios:55900882ebd92236003e99',
    messagingSenderId: '76949227612',
    projectId: 'comparador-ff653',
    storageBucket: 'comparador-ff653.firebasestorage.app',
    iosBundleId: 'com.example.proyectocomparador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCN0j6RSdN3UTVHMPVkVCWIg6Rn-FQgguM',
    appId: '1:76949227612:ios:55900882ebd92236003e99',
    messagingSenderId: '76949227612',
    projectId: 'comparador-ff653',
    storageBucket: 'comparador-ff653.firebasestorage.app',
    iosBundleId: 'com.example.proyectocomparador',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6KJGbIM_bQF9wgH90j6JXmjAnnWEw0i8',
    appId: '1:76949227612:web:cb25955b0192d66a003e99',
    messagingSenderId: '76949227612',
    projectId: 'comparador-ff653',
    authDomain: 'comparador-ff653.firebaseapp.com',
    storageBucket: 'comparador-ff653.firebasestorage.app',
    measurementId: 'G-DRJ8F6DQEQ',
  );
}
